In [2]:
import pandas as pd

def contingency_table(data, col1, col2):
    table = pd.crosstab(data[col1], data[col2])
    return table

# Example usage
data = pd.DataFrame({
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'Preference': ['A', 'B', 'A', 'B', 'A', 'B']
})

table = contingency_table(data, 'Gender', 'Preference')
print(table)



Preference  A  B
Gender          
Female      2  1
Male        1  2


In [3]:
fila1 = [20, 33]
fila2 = [53, 93]

df = pd.DataFrame([fila1, fila2], columns = ['A', 'B'], index = ['X', 'Y'])

print(df)

suma_filas = df.sum(axis = 1)
suma_columnas = df.sum(axis = 0)

print(suma_filas)

print(suma_columnas)

total = df.sum().sum()
print(total)




    A   B
X  20  33
Y  53  93
X     53
Y    146
dtype: int64
A     73
B    126
dtype: int64
199


In [4]:
import numpy as np

obs = np.array([[165, 20, 33], [262, 53, 93]])
exp = np.array([[149, 25, 44], [278, 48, 82]])

xi2 = ((obs - exp)**2 / exp)
print(xi2)

xi2 = xi2.sum()
print(xi2)

[[1.71812081 1.         2.75      ]
 [0.92086331 0.52083333 1.47560976]]
8.38542720415254


In [5]:
from scipy.stats import chi2_contingency

# Crear la tabla de contingencia
data = pd.DataFrame({
    'Sin daño': [165, 262],
    'Daño menor': [20, 53],
    'Daño serio': [33, 93]
}, index=['Usando casco', 'Sin usar casco'])

print(data)

# Realizar la prueba de chi-cuadrado
chi2, p, dof, expected = chi2_contingency(data)

print(f"Chi-cuadrado: {chi2}")
print(f"p-valor: {p}")
print(f"Grados de libertad: {dof}")
print("Frecuencias esperadas:")
print(expected)

# Evaluar el resultado
if p < 0.05:
    print("Hay evidencia de una diferencia en las frecuencias relativas de los diferentes tipos de daño entre los dos grupos.")
else:
    print("No hay evidencia de una diferencia en las frecuencias relativas de los diferentes tipos de daño entre los dos grupos.")

                Sin daño  Daño menor  Daño serio
Usando casco         165          20          33
Sin usar casco       262          53          93
Chi-cuadrado: 8.653833570525151
p-valor: 0.013208208517685652
Grados de libertad: 2
Frecuencias esperadas:
[[148.69968051  25.42172524  43.87859425]
 [278.30031949  47.57827476  82.12140575]]
Hay evidencia de una diferencia en las frecuencias relativas de los diferentes tipos de daño entre los dos grupos.


In [6]:
def rank(list1, list2):

    rank = list1 + list2
    rank.sort()

    list1.sort()
    list2.sort()

    matrix1 = []
    for i in range(len(list1)):
        matrix1.append([list1[i], "x"])

    matrix2 = []
    for i in range(len(list2)):
        matrix2.append([list2[i], "y"])

    matrix = matrix1 + matrix2
    matrix.sort()

    sorted_matrix = []

    # Assign rank
    for i in range(len(matrix)):
        sorted_matrix.append([matrix[i][0], matrix[i][1], i + 1])

    # Add counts for 'x'
    for i in range(len(sorted_matrix)):
        if sorted_matrix[i][1] == "x":
            count = sum(1 for j in range(i) if sorted_matrix[j][1] == "y" and sorted_matrix[j][0] < sorted_matrix[i][0])
            sorted_matrix[i].append(count)
        else:
            sorted_matrix[i].append(0)

    # Print the table
    print("Value\tType\tRank\tCount")
    for row in sorted_matrix:
        print(f"{row[0]}\t{row[1]}\t{row[2]}\t{row[3]}")

    # Calculate sum of ranks for list1 > list2
    sum_ranks = sum(row[2] for row in sorted_matrix if row[1] == "x")
    sum_counts = sum(row[3] for row in sorted_matrix if row[1] != "-")

    print(f"\nsum_ranks list1 > list2 Wx = {sum_ranks}")
    print(f"sum_counts Ux = {sum_counts}")

In [7]:
def sum_rank(rank):
    sum = 0
    for i in rank:
        sum += i
    return sum

In [8]:
def Wilcoxon(nx, ny, rank):
    Wx = sum_rank(rank)
    Ex = nx * (nx + ny + 1) / 2
    Vx = nx * ny * (nx + ny + 1) / 12
    Zx = (Wx - Ex) / (Vx ** 0.5)
    print(f'Wx: {Wx}\nEx: {Ex}\nVx: {Vx}\nZ: {Zx}')
    return Zx

In [9]:
def MannWhitney(nx, ny, rank):
    Ux = sum_rank(rank)
    Ex = nx * ny / 2
    Vx = nx * ny * (nx + ny + 1) / 12
    Zx = (Ux - Ex) / (Vx ** 0.5)
    print(f'Ux: {Ux}\nEx: {Ex}\nVx: {Vx}\nZ: {Zx}')
    return Zx 

In [10]:
def both(nx, ny, rankW, rankU):
    print('Wilcoxon:')
    Wilcoxon(nx, ny, rankW)
    print('\nMann-Whitney:')
    MannWhitney(nx, ny, rankU)

## Ejercio 5

In [11]:
list1 = [3.8, 5.3, 3.5, 4.5, 7.2, 5.1]
list2 = [4, 4, 4, 4, 4, 4]

rank(list1, list2)

Value	Type	Rank	Count
3.5	x	1	0
3.8	x	2	0
4	y	3	0
4	y	4	0
4	y	5	0
4	y	6	0
4	y	7	0
4	y	8	0
4.5	x	9	6
5.1	x	10	6
5.3	x	11	6
7.2	x	12	6

sum_ranks list1 > list2 Wx = 45
sum_counts Ux = 24


In [12]:
both(6, 6, [45], [24])

Wilcoxon:
Wx: 45
Ex: 39.0
Vx: 39.0
Z: 0.9607689228305227

Mann-Whitney:
Ux: 24
Ex: 18.0
Vx: 39.0
Z: 0.9607689228305227


## Ejercicio 6

In [13]:
list1 = [18.3, 16.4, 22.7, 17.8, 18.9, 25.3, 16.1, 24.2]
list2 = [12.6, 14.1, 20.5, 10.7, 15.9, 19.6, 12.9, 15.2, 11.8, 14.70]

rank(list1, list2)

Value	Type	Rank	Count
10.7	y	1	0
11.8	y	2	0
12.6	y	3	0
12.9	y	4	0
14.1	y	5	0
14.7	y	6	0
15.2	y	7	0
15.9	y	8	0
16.1	x	9	8
16.4	x	10	8
17.8	x	11	8
18.3	x	12	8
18.9	x	13	8
19.6	y	14	0
20.5	y	15	0
22.7	x	16	10
24.2	x	17	10
25.3	x	18	10

sum_ranks list1 > list2 Wx = 106
sum_counts Ux = 70


In [14]:
rankW = [9, 10, 11, 12, 13, 16, 17, 18]
rankU = [8, 8, 8, 8, 8, 10, 10, 10]

both(8, 10, rankW, rankU)

# p value
from scipy.stats import norm
p_value = (1 - norm.cdf(2.67))
print(f'p_value: {p_value}')

Wilcoxon:
Wx: 106
Ex: 76.0
Vx: 126.66666666666667
Z: 2.665569949915916

Mann-Whitney:
Ux: 70
Ex: 40.0
Vx: 126.66666666666667
Z: 2.665569949915916
p_value: 0.0037925623476854353


# Ejercicio 7

In [15]:
rankW = [1, 2, 6, 7, 8, 9, 10]
rankU = [3, 3, 3, 3, 3]

both(7, 7, rankW, rankU)

# p value
from scipy.stats import norm
p_value = norm.cdf(-1.21)
print(f'p_value: {p_value}')

Wilcoxon:
Wx: 43
Ex: 52.5
Vx: 61.25
Z: -1.2138654734998857

Mann-Whitney:
Ux: 15
Ex: 24.5
Vx: 61.25
Z: -1.2138654734998857
p_value: 0.11313944644397739


# Ejercicio 8

In [16]:
descuento = [1215, 1698, 2629, 1476, 2404, 2109]
sin_descuento = [1433, 889, 1321, 1842, 711, 1022]

rank(descuento, sin_descuento)

Value	Type	Rank	Count
711	y	1	0
889	y	2	0
1022	y	3	0
1215	x	4	3
1321	y	5	0
1433	y	6	0
1476	x	7	5
1698	x	8	5
1842	y	9	0
2109	x	10	6
2404	x	11	6
2629	x	12	6

sum_ranks list1 > list2 Wx = 52
sum_counts Ux = 31


In [22]:
both(6, 6, rankW = [52], rankU = [31])

Wilcoxon:
Wx: 52
Ex: 39.0
Vx: 39.0
Z: 2.0816659994661326

Mann-Whitney:
Ux: 31
Ex: 18.0
Vx: 39.0
Z: 2.0816659994661326


In [18]:
p_value = 1 - norm.cdf(2.08)
print(f'p_value: {p_value}')

p_value: 0.018762766434937794


## Ejercicio 13

In [19]:
# Datos de las muestras
muestra_X = [-2.604, -2.594, -1.921, -1.756, -1.449, 
             -0.695, -0.676, -0.624, -0.555, -0.157, 
              0.442,  0.786,  0.932,  0.932,  1.691,
              1.697,  1.777,  2.961,  2.976,  6.297]

muestra_Y = [-2.346, -1.113, 0.207, 0.356, 0.873,
              0.897, 1.074, 1.125, 1.629, 1.796,
              2.015, 2.174, 2.315, 2.630, 2.737,
              3.178, 3.610, 3.714, 4.559, 4.847]

rank(muestra_X, muestra_Y)

Value	Type	Rank	Count
-2.604	x	1	0
-2.594	x	2	0
-2.346	y	3	0
-1.921	x	4	1
-1.756	x	5	1
-1.449	x	6	1
-1.113	y	7	0
-0.695	x	8	2
-0.676	x	9	2
-0.624	x	10	2
-0.555	x	11	2
-0.157	x	12	2
0.207	y	13	0
0.356	y	14	0
0.442	x	15	4
0.786	x	16	4
0.873	y	17	0
0.897	y	18	0
0.932	x	19	6
0.932	x	20	6
1.074	y	21	0
1.125	y	22	0
1.629	y	23	0
1.691	x	24	9
1.697	x	25	9
1.777	x	26	9
1.796	y	27	0
2.015	y	28	0
2.174	y	29	0
2.315	y	30	0
2.63	y	31	0
2.737	y	32	0
2.961	x	33	15
2.976	x	34	15
3.178	y	35	0
3.61	y	36	0
3.714	y	37	0
4.559	y	38	0
4.847	y	39	0
6.297	x	40	20

sum_ranks list1 > list2 Wx = 320
sum_counts Ux = 110


In [20]:
rankW = [1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 15, 16, 19, 20, 24, 25, 26, 33, 34, 40]
rankU = [110]

both(20, 20, rankW, rankU)

Wilcoxon:
Wx: 320
Ex: 410.0
Vx: 1366.6666666666667
Z: -2.434508013602067

Mann-Whitney:
Ux: 110
Ex: 200.0
Vx: 1366.6666666666667
Z: -2.434508013602067


## Ejercicio 14

In [21]:
rankW = [3, 5, 7, 8, 9]
rankU = [2, 3, 4, 4, 4]

both(5, 4, rankW, rankU)

Wilcoxon:
Wx: 32
Ex: 25.0
Vx: 16.666666666666668
Z: 1.7146428199482247

Mann-Whitney:
Ux: 17
Ex: 10.0
Vx: 16.666666666666668
Z: 1.7146428199482247
