# 2

In [1]:
import scipy.stats as stats

# Observed frequencies
observed = [115, 85]

# Expected frequencies (assuming the coin is fair)
total_flips = sum(observed)
expected = [total_flips / 2, total_flips / 2]

# Perform chi-square test
chi2_stat, p_val = stats.chisquare(f_obs=observed, f_exp=expected)

# Significance levels
alpha_1 = 0.05
alpha_2 = 0.01

# Print results
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_val}")

Chi-square statistic: 4.5
P-value: 0.033894853524689295


# 3

In [2]:
# Frecuencias observadas de los dígitos
observed_digits = [17, 31, 29, 18, 14, 20, 35, 30, 20, 36]

# Frecuencia esperada para cada dígito (distribución uniforme)
total_digits = sum(observed_digits)
expected_digits = [total_digits / 10] * 10

# Realizar la prueba de chi-cuadrado
chi2_stat_digits, p_val_digits = stats.chisquare(f_obs=observed_digits, f_exp=expected_digits)

# Imprimir resultados
print(f"Chi-square statistic: {chi2_stat_digits}")
print(f"P-value: {p_val_digits}")

Chi-square statistic: 23.279999999999998
P-value: 0.005597179700206032


# 4

In [3]:
# Frecuencias observadas de niños en familias de 5 hijos
observed_families = [18, 56, 110, 88, 40, 8]

# Total de familias encuestadas
total_families = sum(observed_families)

# Probabilidades esperadas bajo la hipótesis de que los nacimientos de varones y mujeres son igualmente probables
probabilities = [stats.binom.pmf(k, 5, 0.5) for k in range(6)]

# Frecuencias esperadas
expected_families = [p * total_families for p in probabilities]

# Grados de libertad
degrees_of_freedom = len(observed_families) - 1

# Realizar la prueba de chi-cuadrado
chi2_stat_families, p_val_families = stats.chisquare(f_obs=observed_families, f_exp=expected_families)

# Imprimir resultados
print(f"Chi-square statistic: {chi2_stat_families}")
print(f"P-value: {p_val_families}")
print(f"Degrees of freedom: {degrees_of_freedom}")

Chi-square statistic: 11.960000000000024
P-value: 0.035340002687752226
Degrees of freedom: 5


# 5

In [4]:
import numpy as np
from scipy.stats import wilcoxon, mannwhitneyu

# Datos de la muestra
tiempos_espera = np.array([3.8, 5.3, 3.5, 4.5, 7.2, 5.1])

# Hipótesis nula: El tiempo de espera medio es de 4 minutos o menos
# Hipótesis alternativa: El tiempo de espera medio es mayor de 4 minutos

# Prueba W de Wilcoxon
w_stat, p_val_w = wilcoxon(tiempos_espera - 4)
print(f"Wilcoxon test statistic: {w_stat}")
print(f"P-value (W test): {p_val_w}")

# Prueba U de Mann-Whitney
# Comparar con una muestra hipotética de tiempos de espera de 4 minutos
hipotetica = np.array([4] * len(tiempos_espera))
u_stat, p_val_u = mannwhitneyu(tiempos_espera, hipotetica, alternative='greater')
print(f"Mann-Whitney U test statistic: {u_stat}")
print(f"P-value (U test): {p_val_u}")

Wilcoxon test statistic: 3.5
P-value (W test): 0.21875
Mann-Whitney U test statistic: 24.0
P-value (U test): 0.1735817526501633


In [5]:
import numpy as np
from scipy.stats import mannwhitneyu, norm

aleacion_I = np.array([18.3, 16.4, 22.7, 17.8, 18.9, 25.3, 16.1, 24.2])
aleacion_II = np.array([12.6, 14.1, 20.5, 10.7, 15.9, 19.6, 12.9, 15.2, 11.8, 14.7])

# Prueba U de Mann-Whitney
u_stat_aleacion, p_val_u_aleacion = mannwhitneyu(aleacion_I, aleacion_II, alternative='greater')
print(f"Mann-Whitney U test statistic: {u_stat_aleacion}")
print(f"P-value (U test): {p_val_u_aleacion}")

nI = len(aleacion_I)
nII = len(aleacion_II)

# Calcular la media esperada (Eu) y la varianza (Vu) de la estadística U
Eu = nI * nII / 2
Vu = nI * nII * (nI + nII + 1) / 12

print(f"Media esperada (Eu): {Eu}")
print(f"Varianza (Vu): {Vu}")

# Calcular el valor Z
Z = (u_stat_aleacion - Eu) / np.sqrt(Vu)
print(f"Z-value: {Z}")

# Calcular el p-valor usando la distribución normal estándar
p_val_manual = 1 - norm.cdf(Z)
print(f"Manual P-value (U test): {p_val_manual}")

Mann-Whitney U test statistic: 70.0
P-value (U test): 0.003108003108003108
Media esperada (Eu): 40.0
Varianza (Vu): 126.66666666666667
Z-value: 2.665569949915916
Manual P-value (U test): 0.003842897027606651


# 11

In [6]:
import numpy as np

import scipy.stats as stats

# Crear la tabla de contingencia
observed_table = np.array([[5, 8, 9, 7],
                           [6, 10, 13, 6]])

# Realizar la prueba de chi-cuadrado de independencia
chi2_stat, p_val, dof, expected_table = stats.chi2_contingency(observed_table)

# Imprimir resultados
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_val}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:")
print(expected_table)

Chi-square statistic: 0.5597467666433183
P-value: 0.9055823451833487
Degrees of freedom: 3
Expected frequencies:
[[ 4.984375  8.15625   9.96875   5.890625]
 [ 6.015625  9.84375  12.03125   7.109375]]


In [7]:
import numpy as np
from scipy.stats import chi2_contingency

# Crear la tabla de contingencia
observed_table = np.array([[165, 20, 33],
                           [262, 53, 93]])

# Realizar la prueba de chi-cuadrado de independencia
chi2_stat, p_val, dof, expected_table = chi2_contingency(observed_table)

# Imprimir resultados
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_val}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:")
print(expected_table)

# Crear una nueva tabla de contingencia solo para los que recibieron daño en la cabeza
observed_head_injury = np.array([[20, 33],
                                 [53, 93]])

# Realizar la prueba de chi-cuadrado de independencia
chi2_stat_head, p_val_head, dof_head, expected_head = chi2_contingency(observed_head_injury)

# Imprimir resultados
print(f"Chi-square statistic (head injury): {chi2_stat_head}")
print(f"P-value (head injury): {p_val_head}")
print(f"Degrees of freedom (head injury): {dof_head}")
print("Expected frequencies (head injury):")
print(expected_head)

Chi-square statistic: 8.653833570525151
P-value: 0.013208208517685652
Degrees of freedom: 2
Expected frequencies:
[[148.69968051  25.42172524  43.87859425]
 [278.30031949  47.57827476  82.12140575]]
Chi-square statistic (head injury): 0.000369765703052419
P-value (head injury): 0.9846581896143868
Degrees of freedom (head injury): 1
Expected frequencies (head injury):
[[19.44221106 33.55778894]
 [53.55778894 92.44221106]]


# 13

In [19]:
import numpy as np
from scipy.stats import rankdata, norm

# Datos de las muestras
muestra_X = np.array([-2.604, -2.594, -1.921, -1.756, -1.449, -2.346, -1.113, 0.207, 0.356, 0.873,
                      -0.695, -0.676, -0.624, -0.555, -0.157, 0.897, 1.074, 1.125, 1.629, 1.796])
muestra_Y = np.array([0.442, 0.786, 0.932, 0.932, 1.691, 2.015, 2.174, 2.315, 2.630, 2.737,
                      1.697, 1.777, 2.961, 2.976, 6.297, 3.178, 3.610, 3.714, 4.559, 4.847])


# Prueba W de Wilcoxon
w_stat, p_val_w = wilcoxon(muestra_X, muestra_Y)
print(f"Wilcoxon test statistic: {w_stat}")
print(f"P-value (W test): {p_val_w}")
# Realizar la prueba U de Mann-Whitney

u_stat, p_val = mannwhitneyu(muestra_X, muestra_Y, alternative='two-sided', use_continuity=False)

# Imprimir resultados
print(f"Mann-Whitney U test statistic: {u_stat}")
print(f"P-value: {p_val}")

n_X = len(muestra_X)
n_Y = len(muestra_Y)

eu = n_X * n_Y / 2
print(f"Media esperada (Eu): {eu}")

vu = n_X * n_Y * (n_X + n_Y + 1) / 12
print(f"Varianza (Vu): {vu}")


# Calcular la estadística Z
Z = (u_stat - eu) / np.sqrt(vu)
print(f"Z-value: {Z}")

# Calcular el p-valor usando la distribución normal estándar
p_val_manual = 2 * (1 - norm.cdf(abs(Z)))
print(f"Manual P-value (U test): {p_val_manual}")



# Combinar las muestras
combined_samples = np.concatenate([muestra_X, muestra_Y])

# Calcular los rangos
ranks = rankdata(combined_samples)

# Suma de rangos para la muestra X
ranks_X = ranks[:len(muestra_X)]
T_X = np.sum(ranks_X)

# Calcular la media y la varianza de la suma de rangos
n_X = len(muestra_X)
n_Y = len(muestra_Y)
E_T_X = n_X * (n_X + n_Y + 1) / 2
V_T_X = n_X * n_Y * (n_X + n_Y + 1) / 12

# Calcular la estadística Z
Z_X = (T_X - E_T_X) / np.sqrt(V_T_X)

# Calcular el p-valor
p_val_Z_X = 2 * (1 - norm.cdf(abs(Z_X)))

# Imprimir resultados
print(f"Suma de rangos para la muestra X: {T_X}")
print(f"Media esperada de la suma de rangos: {E_T_X}")
print(f"Varianza de la suma de rangos: {V_T_X}")
print(f"Estadística Z: {Z_X}")
print(f"P-valor: {p_val_Z_X}")

Wilcoxon test statistic: 0.0
P-value (W test): 1.9073486328125e-06
Mann-Whitney U test statistic: 23.0
P-value: 1.683758478084451e-06
Media esperada (Eu): 200.0
Varianza (Vu): 1366.6666666666667
Z-value: -4.787865760084065
Manual P-value (U test): 1.6856433537881799e-06
Suma de rangos para la muestra X: 233.0
Media esperada de la suma de rangos: 410.0
Varianza de la suma de rangos: 1366.6666666666667
Estadística Z: -4.787865760084065
P-valor: 1.6856433537881799e-06


# 14

In [12]:
import numpy as np
from scipy.stats import mannwhitneyu, norm

# Datos de la edad al diagnóstico de diabetes tipo II
hombres = np.array([19, 22, 16, 29, 24])
mujeres = np.array([20, 11, 17, 12])

# Realizar la prueba U de Mann-Whitney
u_stat, p_val = mannwhitneyu(hombres, mujeres, alternative='two-sided', method='asymptotic', use_continuity=False)

# Imprimir resultados
print(f"Mann-Whitney U test statistic: {u_stat}")
print(f"P-value: {p_val}")

n_h = len(hombres)
n_m = len(mujeres)

e = n_h * n_m / 2
print(f"Media esperada (Eu): {e}")

v = (n_h * n_m) * (n_h + n_m + 1) / 12
print(f"Varianza (Vu): {v}")

z = (u_stat - e) / np.sqrt(v)
print(f"Z-value: {z}")

p_val_manual = 2 * norm.cdf(-z)
print(f"Manual P-value (U test): {p_val_manual}")

Mann-Whitney U test statistic: 17.0
P-value: 0.0864107329737
Media esperada (Eu): 10.0
Varianza (Vu): 16.666666666666668
Z-value: 1.7146428199482247
Manual P-value (U test): 0.0864107329737
